name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.DEPLOY }}
          BRANCH: main
          FOLDER: dist
          REPOSITORY_NAME: tonytang0909-grl/person
